apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ackee
  labels:
    app: redis-ackee
    role: server
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-ackee
      role: server
      tier: backend
  template:
    metadata:
      labels:
        app: redis-ackee
        role: server
        tier: backend
    spec:
      containers:
      - name: redis-ackee
        image: ackee/docker-redis:5.0
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-ackee
  labels:
    app: redis-ackee
    role: server
    tier: backend
spec:
  selector:
    app: redis-ackee
    role: server
    tier: backend
  ports:
    - port: 6379
      targetPort: 6379
  type: NodePort
